### ISSUE TITLE
Redesign NavBar.

### ISSUE THREAD

**Issue by Aksn09** [praveenscience/Certificate-Generator-UI#3]
Hey Praveen,

I would like to redesign the nav bar and also the main page image is not visible after cloning the repo would like to fix that too.

**Comment by praveenscience** [comment]
Hi @Aksn09, do you understand what exactly is this repo about? 😅

Also please tell me with a screenshot, maybe, what do you mean by "the main page image is not visible after cloning the repo would like to fix that too".

**Comment by Aksn09** [comment]
Hey, sorry I thought it was part of the Hacktoberfest. I attended one of your sessions and came to know about this repo.

![image](https://user-images.githubusercontent.com/61744786/136554294-342bb76f-1843-4ac6-a755-0a3e4ba1653b.png)

Please refer to this image.

**Comment by praveenscience** [comment]
Yes please go ahead and create one on your own and raise a PR. Thanks.

**Comment by Aksn09** [comment]
Sure, on it.

**Comment by RiyaGupta89** [comment]
@praveenscience Sir can you assign me some task to work on? I would like to contribute to this repository.

**Comment by praveenscience** [comment]
@RiyaGupta89 Just follow the contribution instructions and start with it.
